secondary script retry logic fixed

diff --git a/.github/workflows/main_2.yml b/.github/workflows/main_2.yml
--- a/.github/workflows/main_2.yml
+++ b/.github/workflows/main_2.yml
@@ -56,4 +56,6 @@ jobs:
           retry_wait_seconds: 90
           command: |
             python ./private_script_storage/main.py >& /dev/null
-            echo "length of gt: $(wc -m gt.txt | sed 's/gt.txt//g')"          
+            test -e gt.txt && \
+            echo "length of gt: $(wc -m gt.txt | sed 's/gt.txt//g')" || \
+            echo "gt not found. exitting..." >&2 | exit 1      
